env: "local"
storage_path: ".storage/fileService.db"
migration_path: ".migrations"
grpc:
  port: 44044
  timeout: 10h
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 1234
  database: fileservices
